name: Production pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  deploy:
    runs-on: whale
    steps:
    - uses: actions/checkout@master
    - name: deploy
      env:
        TARANTOOL_USER_NAME: ${{ secrets.TARANTOOL_USER_NAME }}
        TARANTOOL_USER_PASSWORD: ${{ secrets.TARANTOOL_USER_PASSWORD }}
      run: |
        docker-compose -f docker-kafka.yaml up -d
        docker-compose -f docker-tarantool.yaml up -d
